### PR TITLE
Implement random image service

### PR DESCRIPTION
**Pull request by flashback2k14**
@lyio @hetec for **quick** review

### CODE REVIEW

**Comment by flashback2k14** [comment]
ignore travis - the testing branch isn't merged into the master at the moment

**Comment by lyio** [comment]
Returning an image turned out to be that easy after all?

**Comment by lyio** [comment]
I haven't tried this but lgtm so far

**Comment by flashback2k14** [comment]
yeah, this is the whole magic. ;-)

**Pull request merged**
